# Generated by Django 5.1.7 on 2025-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar (US$)'), ('GBP', 'Libra (£)')], default='EUR', max_length=3),
        ),
    ]
